from setuptools import setup

setup(
    name="trident-core",
    version="0.1.0",
    description="A declarative deep learning framework",
    url="https://github.com/fdschmidt93/trident",
    author="Fabian David Schmidt",
    author_email="fabian@informatik.uni-mannheim.de",
    license="Apache",
    packages=["pyexample"],
    install_requires=[
        "torch>=1.8.2",
        "torchvision>=0.9.1",
        "pytorch-lightning>=1.5.2",
        "hydra-core==1.1.0",
        "hydra-colorlog==1.1.0",
        "hydra-optuna-sweeper==1.1.0",
        "numpy>=1.17",
        "python-dotenv",
        "rich",
        "scikit-learn",
        "seaborn",
    ],
    classifiers=[
        "Environment :: Console",
        "Natural Language :: English",
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: Apache Software License",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
    ],
)
