datamodule.datasets:
  # for this config
  # do config callback as specified below
  _target_: trident.utils.hydra.expand
  merge_keys: ["train", "val", "test"]
  gen_keys: false

datamodule.dataloaders:
  _target_: trident.utils.hydra.expand
  merge_keys: ["train", "val", "test"]
  gen_keys: true

module.evaluation.prepare:
  _target_: trident.utils.hydra.expand
  merge_keys: ["val", "test"]
  gen_keys: true

module.evaluation.step_outputs:
  _target_: trident.utils.hydra.expand
  merge_keys: ["val", "test"]
  gen_keys: true

module.evaluation.metrics:
  _target_: trident.utils.hydra.expand
  merge_keys: ["val", "test"]
  gen_keys: true
