_recursive_: false
_target_: src.modules.base.TridentModule

defaults:
# interleaved with setup so instantiated later (recursive false)
- /optimizer: ${optimizer}
- /scheduler: ${scheduler}
- /evaluation: question_answering

model:
  _target_: transformers.AutoModelForQuestionAnswering.from_pretrained
  pretrained_model_name_or_path: ???
