defaults:
 # base trident datamodule configuration
 - trident

dataset_cfg:
  _target_: datasets.load.load_dataset
  _method_: # get methods of _target_ object
    map: # dataset.map -> tokenization
      # kwargs for dataset.map
      function:
        _target_: src.utils.hydra.partial
        _partial_: src.utils.preprocessing.text_classification
        column_names:
          text: premise
          text_pair: hypothesis
          labels: label

  path: glue
  name: mnli

  train:
    split: train
  val:
    # Huggingface datasets syntax to concatenate these splits
    split: "validation_mismatched+validation_matched"
  test:
    path: xnli
    name: de
    split: test
