_target_: src.datamodules.squad.SQuADDataModule
_recursive_: false

dataset_cfg:
  _target_: datasets.load.load_dataset
  _method_:
    map:
      function:
        # "When splitting up a long document into chunks, how much stride to take between chunks."
        tokenizer:
          stride: 128
          return_overflowing_tokens: true  # do not change
          return_offsets_mapping: true  # do not change
          padding: "max_length"
          return_overflowing_tokens: true
          return_offsets_mapping: true
        column_names:
          text: premise
          text_pair: hypothesis
          labels: label

  path: squad

  train:
    _method_:
      map:
        function:
          _target_: src.utils.hydra.partial
          _partial_: src.utils.preprocessing.question_answering_train

    split: train

  val:
    _method_:
      map:
        function:
          _target_: src.utils.hydra.partial
          _partial_: src.utils.preprocessing.question_answering_val_test
    split: validation
